# Site settings
title:          Douglas Motta
description:    "Blog para tutoriais sobre programação"
baseurl:        "/blog"
url:            "https://douglasramalho.github.io"

# Author
author:
  name:         Douglas Motta
  url:          
  email:        douglas1102rm@hotmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
